<h1>Liens doc</h1>

<ul>
	<li><a href="http://framework.zend.com/manual/2.3/en/modules/zend.permissions.rbac.intro.html">RBAC</a> : pour une gestion simple des droits par role</li>
	<li><a href="http://framework.zend.com/manual/2.3/en/modules/zend.filter.set.html">Filter</a> : pour filtrer des données (formulaire ou autre) => peut être utilisé avec <a href="http://framework.zend.com/manual/2.0/en/modules/zend.input-filter.intro.html">InputFilter</a>
	<li><a href="http://framework.zend.com/manual/2.0/en/modules/zend.validator.html">Validator</a> : pour valider des données (formulaire ou autre) => peut être utilisé avec <a href="http://framework.zend.com/manual/2.0/en/modules/zend.input-filter.intro.html">InputFilter</a>
	<li><a href="https://www.apigility.org/">Apigility</a> : pour la partie API
</ul> 